site_name: lernOS Convention 2025 Dokumentation
site_url: https://cogneon.github.io/loscon25doku/de/
docs_dir: src
site_dir: ../docs/de
edit_uri: ''

nav:
    - Willkommen: index.md
    - Impulsvorträge:
      - Simon Dückert - Ni lernOS - Wenn wir nur wüssten, was wir wissen: 1-1-dueckert.md
      - Bettina Laugwitz - Mind the AI Safety Gap: 1-2-laugwitz.md
    - Lightning Talks:
      - Nele Hirsch - Modellierung als 'Mind the knowledge gap'-Ansatz bei der Interaktion mit KI-Sprachmodellen: 2-1-hirsch.md
      - Oliver Fischer - Selbstorganisation zum Anfassen – Was Teams wirklich stark macht: 2-2-fischer.md
      - Victoria Köstner - Mind the Knowledge Gap – are your lessons really learned?: 2-3-kostner.md
      - Daniel Prial - KI - Überbrücken wir die Kommunikations-Gaps oder klingen wir alle wie Roboter?: 2-4-prial.md
      - Jan Bretschneider - Wissenslücken schließen durchs Lösen von Problemen: 2-5-bretschneider.md
      - Felix Harling - Was Organisationen von Pilzen lernen können.: 2-6-harling.md
      - Harald Schirmer - The Knowledge Gap in Management: 2-7-schirmer.md
      - Dajana Prellwitz - Wissenslücken füllt man nicht mit Tools – Wissensmanagement neu gedacht bei NETZSCH: 2-8-prellwitz.md
      - Armin Zoike - Mind the AI Gap - Warum dokmentiertes Wissen das wichtigste Asset im KI-Zeitalter ist und wie man es einfach aufbaut: 2-9-zoike.md
      - Thomas Jenewein - Von Wissenslücken zu Veränderungserfolg – Wie Change Management Wissen und Emotionen verbindet: 2-10-jenewein.md
    - Sessions und  Workshops:
      - Marcel Kirchner, Thomas Schmidt - Never Prompt Alone! Erfahrungsbericht zum globalen Einsatz des lernOS KI-Leitfadens: 3-1-1-kirchner-schmidt.md
      - Simone Engelhard, Simon Qualmann - Der Working-Learning Gap – Zwischen Alltagsstress und Lernanspruch: 3-1-2-engelhard-qualmann.md
      - Sven Semet - Wie wichtig sind digitale Assistenten für die Zukunft von Learning & Development?: 3-1-3-semet.md
      - Achim Brueck - Was braucht eine Community, die "unbekanntes Unwissen" erkunden will?: 3-1-4-brueck.md
      - Magnus Rode, Daniel Prial - The Human & Artificial Intelligence Gap – Impact der KI auf die (digitale) Zusammenarbeit: 3-2-1-rode-prial.md
      - Oliver Fischer - Selbstorganisation sichtbar machen – Praxiserfahrungen mit dem 6K-Modell der LV 1871: 3-2-2-fischer.md
      - Thomas Jenewein - Use Cases und Szenarien für KI Agenten in Learning & Development entlang des ADDIE: 3-2-3-jenewein.md
      - Armin Zoike - Wie kann KI den Austausch von Wissen und Informationen und die Kommunikation in Organisationen verändern?: 3-2-4-zoike.md
      - Susann Schulz - Mind the Diversity Gap - Wie KI unsere blinden Flecken re(pro)duziert: 3-3-1-schulz.md
      - Martin Harnisch - Enterprise Wikis - Warum alle alles lesen und bearbeiten können sollten: 3-3-2-harnisch.md
      - Victoria Köstner - Schließe die Wissenslücke in deiner Projektwelt - bewahre Projektwissen strukturiert und ganzheitlich!: 3-3-3-koestner.md
      - Harald Schirmer - How to close the Knowledge Gap in Management: 3-3-4-schirmer.md
      - Björn Schotte - Der große Technologie-Struktur-Gap - Warum KI nicht an Technologie, sondern an Strukturen scheitert: 3-4-1-schotte.md
      - Andreas Trebing, Felix Harling - The Second Brain Gap - Sammelst du noch oder denkst du schon?: 3-4-2-harling-trebing.md
      - Brigitte Lüdecke, Harald Schirmer - Digitale Souveränität DigitalBewusstHandeln: 3-4-3-luedecke-schirmer.md
      - Martin Heider - Zukunft der Softwareentwicklung in 2035. Wie erreichen wir Heaven statt Hell: 3-4-4-heider.md
    - Podcasts:
      - Silvia Roderus - Expert Debriefing unplugged: 4-1-roderus.md
      - Gabriele Schobess, Katharina Nolden - lernOS für gesellschaftliches Engagement und Beteiligung: 4-2-schobess-nolden.md
      - Simon Dückert, Christian Kaiser - Peer Learning groß machen: 4-3-dueckert-kaiser.md
      - Oliver Grobs, Tobias Gerndt - Sharing is Caring - Teilen macht reich: 4-4-grobs-gerndt.md
    - Download:
      - PDF-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon25-AI-Documentation-de.pdf
      - Word-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon25-AI-Documentation-de.docx
      - HTML-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon25-AI-Documentation-de.html
      - E-Book-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon25-AI-Documentation-de.epub
      - Markdown: https://github.com/cogneon/loscon25doku/blob/master/de/loscon25-AI-Documentation-de.md



theme:
    name: 'material'
#    custom_dir: src/overrides
    palette:
        primary: black
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate
      - search.share

#extra_css:
#  - stylesheets/extra.css

repo_name: 'cogneon/loscon25doku'
repo_url: 'https://github.com/cogneon/loscon25doku'

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/groups/8682361/'
    generator: false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
plugins:
  - search