site_name: lernOS Convention 2025 Dokumentation
site_url: https://cogneon.github.io/loscon25doku/de/
docs_dir: src
site_dir: ../docs/de
edit_uri: ''

nav:
    - Willkommen: index.md
    - Impulsvorträge:
      - Simon Dückert - Ni lernOS - Wenn wir nur wüssten, was wir wissen: 1-1.md
      - Bettina Laugwitz - Mind the AI Safety Gap: 1-2.md
    - Lightning Talks:
      - Nele Hirsch - Modellierung als 'Mind the knowledge gap'-Ansatz bei der Interaktion mit KI-Sprachmodellen: 2-1.md
      - Oliver Fischer - Selbstorganisation zum Anfassen – Was Teams wirklich stark macht: 2-2.md
      - Victoria Köstner - Mind the Knowledge Gap – are your lessons really learned?: 2-3.md
      - Daniel Prial - KI - Überbrücken wir die Kommunikations-Gaps oder klingen wir alle wie Roboter?: 2-4.md
      - Jan Bretschneider - Wissenslücken schließen durchs Lösen von Problemen: 2-5.md
      - Felix Harling - Was Organisationen von Pilzen lernen können.: 2-6.md
      - Harald Schirmer - The Knowledge Gap in Management: 2-7.md
      - Dajana Prellwitz - Wissenslücken füllt man nicht mit Tools – Wissensmanagement neu gedacht bei NETZSCH: 2-8.md
      - Armin Zoike - Mind the AI Gap - Warum dokmentiertes Wissen das wichtigste Asset im KI-Zeitalter ist und wie man es einfach aufbaut: 2-9.md
      - Thomas Jenewein - Von Wissenslücken zu Veränderungserfolg – Wie Change Management Wissen und Emotionen verbindet: 2-10.md
#    - Sessions und  Workshops:
#   - Podcasts:
    - Download:
      - Word-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon-Documentation-de.docx
      - HTML-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon-Documentation-de.html
      - Markdown: https://github.com/cogneon/loscon25doku/blob/master/de/loscon-Documentation-de.md



theme:
    name: 'material'
#    custom_dir: src/overrides
    palette:
        primary: black
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate
      - search.share

#extra_css:
#  - stylesheets/extra.css

repo_name: 'cogneon/loscon25doku'
repo_url: 'https://github.com/cogneon/loscon25doku'

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/groups/8682361/'
    generator: false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
plugins:
  - search