site_name: lernOS Convention 2025 Dokumentation
site_url: https://cogneon.github.io/loscon25doku/de/
docs_dir: src
site_dir: ../docs/de
edit_uri: ''

nav:
    - Willkommen: index.md
    - Impulsvorträge:
      - Simon Dückert - Ni lernOS - Wenn wir nur wüssten, was wir wissen: 1-1-dueckert.md
      - Bettina Laugwitz - Mind the AI Safety Gap: 1-2-laugwitz.md
    - Lightning Talks:
      - Nele Hirsch - Modellierung als 'Mind the knowledge gap'-Ansatz bei der Interaktion mit KI-Sprachmodellen: 2-1-hirsch.md
      - Oliver Fischer - Selbstorganisation zum Anfassen – Was Teams wirklich stark macht: 2-2-fischer.md
      - Victoria Köstner - Mind the Knowledge Gap – are your lessons really learned?: 2-3-kostner.md
      - Daniel Prial - KI - Überbrücken wir die Kommunikations-Gaps oder klingen wir alle wie Roboter?: 2-4-prial.md
      - Jan Bretschneider - Wissenslücken schließen durchs Lösen von Problemen: 2-5-bretschneider.md
      - Felix Harling - Was Organisationen von Pilzen lernen können.: 2-6-harling.md
      - Harald Schirmer - The Knowledge Gap in Management: 2-7-schirmer.md
      - Dajana Prellwitz - Wissenslücken füllt man nicht mit Tools – Wissensmanagement neu gedacht bei NETZSCH: 2-8-prellwitz.md
      - Armin Zoike - Mind the AI Gap - Warum dokmentiertes Wissen das wichtigste Asset im KI-Zeitalter ist und wie man es einfach aufbaut: 2-9-zoike.md
      - Thomas Jenewein - Von Wissenslücken zu Veränderungserfolg – Wie Change Management Wissen und Emotionen verbindet: 2-10-jenewein.md
#   - Sessions und  Workshops:
    - Podcasts:
      - Silvia Roderus - Expert Debriefing unplugged: 4-1-roderus.md
      - Gabriele Schobess, Katharina Nolden - lernOS für gesellschaftliches Engagement und Beteiligung: 4-2-schobess-nolden.md
      - Simon Dückert, Christian Kaiser - Peer Learning groß machen: 4-3-dueckert-kaiser.md
      - Oliver Grobs, Tobias Gerndt - Sharing is Caring - Teilen macht reich: 4-4-grobs-gerndt.md
    - Download:
      - Word-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon-Documentation-de.docx
      - HTML-Version: https://github.com/cogneon/loscon25doku/blob/master/de/loscon-Documentation-de.html
      - Markdown: https://github.com/cogneon/loscon25doku/blob/master/de/loscon-Documentation-de.md



theme:
    name: 'material'
#    custom_dir: src/overrides
    palette:
        primary: black
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate
      - search.share

#extra_css:
#  - stylesheets/extra.css

repo_name: 'cogneon/loscon25doku'
repo_url: 'https://github.com/cogneon/loscon25doku'

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/groups/8682361/'
    generator: false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
plugins:
  - search