site_name: lernOS Convention 2025 Dokumentation
site_url: https://cogneon.github.io/loscon25doku/de/
docs_dir: src
site_dir: ./docs/de
edit_uri: ''

nav:
    - Willkommen: index.md
    - Impulsvorträge:
      - Simon Dückert - Ni lernOS - Wenn wir nur wüssten, was wir wissen: 1-1.md
      - Bettina Laugwitz - Mind the AI Safety Gap: 1-2.md
#    - Lightning Talks:
#    - Sessions und  Workshops:
#   - Podcasts:


theme:
    name: 'material'
#    custom_dir: src/overrides
    palette:
        primary: black
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate
      - search.share

#extra_css:
#  - stylesheets/extra.css

repo_name: 'cogneon/loscon25doku'
repo_url: 'https://github.com/cogneon/loscon25doku'

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/groups/8682361/'
    generator: false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
plugins:
  - search