site_name: loscon25 Un-Konferenzband
site_url: https://cogneon.github.io/loscon25doku
docs_dir: src
site_dir: ../docs/de
edit_uri: ''

nav:
    - Startseite: index.md
    - Impulsvorträge: 1-0-keynotes.md
    - Lightning Talks: 2-0-lightning-talks.md
    - Sessions & Workshops: 3-0-sessions-workshops.md
    - Podcasts: 4-0-podcasts.md
    - Teilgeber:innen: 5-0-participants.md
    - Anhang: 6-0-appendix.md
    - Download:
      - PDF-Version: https://github.com/cogneon/loscon25doku/blob/master/de/build/loscon-Documentation-de.pdf
      - Word-Version: https://github.com/cogneon/loscon25doku/blob/master/de/build/loscon-Documentation-de.docx
      - HTML-Version: https://github.com/cogneon/loscon25doku/blob/master/de/build/loscon-Documentation-de.html
      - E-Book (epub): https://github.com/cogneon/loscon25doku/blob/master/de/build/loscon-Documentation-de.epub
    - Links:
      - loscon Infoseiten: https://loscon.lernos.org
      - CONNECT Community: https://community.cogneon.de

theme:
    name: material
    custom_dir: src/overrides
    palette:
        primary: black
        accent: red
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/matomo.js

repo_name: 'cogneon/loscon25doku'
repo_url: 'https://github.com/cogneon/loscon25doku'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    generator: false

copyright: cogneon.de/impressum

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - rss:
      abstract_chars_count: -1  # -1 for full content